/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppBackupsRouteImport } from './routes/_app.backups'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBranchesRouteImport } from './routes/_app.branches'
import { Route as AppBusinessesRouteImport } from './routes/_app.businesses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDownloadsRouteImport } from './routes/_app.downloads'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppLicenseRouteImport } from './routes/_app.license'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthSessionExpiredRouteImport } from './routes/_auth.session-expired'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth.two-factor'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin.admin.analytics'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin.admin.audit-logs'
import { Route as AdminAdminBackupsRouteImport } from './routes/_admin.admin.backups'
import { Route as AdminAdminDevicesRouteImport } from './routes/_admin.admin.devices'
import { Route as AdminAdminFeatureFlagsRouteImport } from './routes/_admin.admin.feature-flags'
import { Route as AdminAdminLicensesRouteImport } from './routes/_admin.admin.licenses'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin.admin.notifications'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin.reports'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminShopsRouteImport } from './routes/_admin.admin.shops'
import { Route as AdminAdminSystemHealthRouteImport } from './routes/_admin.admin.system-health'
import { Route as AdminAdminUpdatesRouteImport } from './routes/_admin.admin.updates'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth.auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessesRoute = AppBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppLicenseRoute = AppLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBackupsRoute = AdminAdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDevicesRoute = AdminAdminDevicesRouteImport.update({
  id: '/admin/devices',
  path: '/admin/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFeatureFlagsRoute = AdminAdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLicensesRoute = AdminAdminLicensesRouteImport.update({
  id: '/admin/licenses',
  path: '/admin/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminShopsRoute = AdminAdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSystemHealthRoute = AdminAdminSystemHealthRouteImport.update({
  id: '/admin/system-health',
  path: '/admin/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUpdatesRoute = AdminAdminUpdatesRouteImport.update({
  id: '/admin/updates',
  path: '/admin/updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/ai': typeof AppAiRoute
  '/backups': typeof AppBackupsRoute
  '/billing': typeof AppBillingRoute
  '/branches': typeof AppBranchesRoute
  '/businesses': typeof AppBusinessesRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/downloads': typeof AppDownloadsRoute
  '/inventory': typeof AppInventoryRoute
  '/license': typeof AppLicenseRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/session-expired': typeof AuthSessionExpiredRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/backups': typeof AdminAdminBackupsRoute
  '/admin/devices': typeof AdminAdminDevicesRoute
  '/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/admin/licenses': typeof AdminAdminLicensesRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/shops': typeof AdminAdminShopsRoute
  '/admin/system-health': typeof AdminAdminSystemHealthRoute
  '/admin/updates': typeof AdminAdminUpdatesRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/ai': typeof AppAiRoute
  '/backups': typeof AppBackupsRoute
  '/billing': typeof AppBillingRoute
  '/branches': typeof AppBranchesRoute
  '/businesses': typeof AppBusinessesRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/downloads': typeof AppDownloadsRoute
  '/inventory': typeof AppInventoryRoute
  '/license': typeof AppLicenseRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/session-expired': typeof AuthSessionExpiredRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/backups': typeof AdminAdminBackupsRoute
  '/admin/devices': typeof AdminAdminDevicesRoute
  '/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/admin/licenses': typeof AdminAdminLicensesRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/shops': typeof AdminAdminShopsRoute
  '/admin/system-health': typeof AdminAdminSystemHealthRoute
  '/admin/updates': typeof AdminAdminUpdatesRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/backups': typeof AppBackupsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/businesses': typeof AppBusinessesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/license': typeof AppLicenseRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/session-expired': typeof AuthSessionExpiredRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/_admin/admin/backups': typeof AdminAdminBackupsRoute
  '/_admin/admin/devices': typeof AdminAdminDevicesRoute
  '/_admin/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/_admin/admin/licenses': typeof AdminAdminLicensesRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/shops': typeof AdminAdminShopsRoute
  '/_admin/admin/system-health': typeof AdminAdminSystemHealthRoute
  '/_admin/admin/updates': typeof AdminAdminUpdatesRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai'
    | '/backups'
    | '/billing'
    | '/branches'
    | '/businesses'
    | '/dashboard'
    | '/devices'
    | '/downloads'
    | '/inventory'
    | '/license'
    | '/notifications'
    | '/pos'
    | '/reports'
    | '/sales'
    | '/security'
    | '/settings'
    | '/support'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/two-factor'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/backups'
    | '/admin/devices'
    | '/admin/feature-flags'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/system-health'
    | '/admin/updates'
    | '/admin/users'
    | '/auth/callback'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai'
    | '/backups'
    | '/billing'
    | '/branches'
    | '/businesses'
    | '/dashboard'
    | '/devices'
    | '/downloads'
    | '/inventory'
    | '/license'
    | '/notifications'
    | '/pos'
    | '/reports'
    | '/sales'
    | '/security'
    | '/settings'
    | '/support'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/two-factor'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/backups'
    | '/admin/devices'
    | '/admin/feature-flags'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/system-health'
    | '/admin/updates'
    | '/admin/users'
    | '/auth/callback'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_app/account'
    | '/_app/ai'
    | '/_app/backups'
    | '/_app/billing'
    | '/_app/branches'
    | '/_app/businesses'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/downloads'
    | '/_app/inventory'
    | '/_app/license'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/users'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/session-expired'
    | '/_auth/two-factor'
    | '/_auth/verify-email'
    | '/_admin/admin/analytics'
    | '/_admin/admin/audit-logs'
    | '/_admin/admin/backups'
    | '/_admin/admin/devices'
    | '/_admin/admin/feature-flags'
    | '/_admin/admin/licenses'
    | '/_admin/admin/notifications'
    | '/_admin/admin/reports'
    | '/_admin/admin/settings'
    | '/_admin/admin/shops'
    | '/_admin/admin/system-health'
    | '/_admin/admin/updates'
    | '/_admin/admin/users'
    | '/_auth/auth/callback'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/businesses': {
      id: '/_app/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AppBusinessesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/license': {
      id: '/_app/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AppLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/session-expired': {
      id: '/_auth/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/audit-logs': {
      id: '/_admin/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/backups': {
      id: '/_admin/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminAdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/devices': {
      id: '/_admin/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminAdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/feature-flags': {
      id: '/_admin/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminAdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/licenses': {
      id: '/_admin/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminAdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/shops': {
      id: '/_admin/admin/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminAdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/system-health': {
      id: '/_admin/admin/system-health'
      path: '/admin/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminAdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/updates': {
      id: '/_admin/admin/updates'
      path: '/admin/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminAdminUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminBackupsRoute: typeof AdminAdminBackupsRoute
  AdminAdminDevicesRoute: typeof AdminAdminDevicesRoute
  AdminAdminFeatureFlagsRoute: typeof AdminAdminFeatureFlagsRoute
  AdminAdminLicensesRoute: typeof AdminAdminLicensesRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminShopsRoute: typeof AdminAdminShopsRoute
  AdminAdminSystemHealthRoute: typeof AdminAdminSystemHealthRoute
  AdminAdminUpdatesRoute: typeof AdminAdminUpdatesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminBackupsRoute: AdminAdminBackupsRoute,
  AdminAdminDevicesRoute: AdminAdminDevicesRoute,
  AdminAdminFeatureFlagsRoute: AdminAdminFeatureFlagsRoute,
  AdminAdminLicensesRoute: AdminAdminLicensesRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminShopsRoute: AdminAdminShopsRoute,
  AdminAdminSystemHealthRoute: AdminAdminSystemHealthRoute,
  AdminAdminUpdatesRoute: AdminAdminUpdatesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAiRoute: typeof AppAiRoute
  AppBackupsRoute: typeof AppBackupsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppBusinessesRoute: typeof AppBusinessesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLicenseRoute: typeof AppLicenseRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAiRoute: AppAiRoute,
  AppBackupsRoute: AppBackupsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppBusinessesRoute: AppBusinessesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLicenseRoute: AppLicenseRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
